### ISSUE TITLE
Transactions didn't work.

### ISSUE THREAD

**Issue by cryptcoin-junkey** [bitbankinc/node-bitbankcc#4]
```
onst bitbank = require('node-bitbankcc');
const api = bitbank.publicApi();

api.getTransactions('mona_jpy').then(console.log);
```

returns 404 error like this.

```
rror: StatusCodeError: 404 - "{\"success\":0,\"data\":{\"code\":10000}}"
Unhandled rejection Error: 404
    at /home/ubuntu/influx-study/node_modules/node-bitbankcc/lib/publicApi.js:23:13
    at tryCatcher (/home/ubuntu/influx-study/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/influx-study/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ubuntu/influx-study/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ubuntu/influx-study/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/influx-study/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/ubuntu/influx-study/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ubuntu/influx-study/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/ubuntu/influx-study/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

Is this a temporary issue on the server side? Or some APIs were modified?

**Comment by cryptcoin-junkey** [comment]
`getTicker()` works well.

```
api.getTicker('mona_jpy').then(console.log);
```

The result.

```
{ sell: '53.759',
  buy: '53.438',
  high: '58.400',
  low: '45.000',
  last: '56.199',
  vol: '2486.2455',
  timestamp: 1505977025297 }
```

**Comment by cryptcoin-junkey** [comment]
I run it with `NODE_DEBUG=request`

Looks the wrong URL passed.
 
```
REQUEST { uri: 'https://public.bitbank.cc/mona_jpy/transactions/undefined',
  callback: [Function: RP$callback],
  transform: undefined,
  simple: true,
  resolveWithFullResponse: false,
  transform2xxOnly: false }
REQUEST make request https://public.bitbank.cc/mona_jpy/transactions/undefined
REQUEST onRequestResponse https://public.bitbank.cc/mona_jpy/transactions/undefined 404 { 'content-type': 'text/plain',
  'content-length': '35',
  connection: 'close',
  'last-modified': 'Sun, 08 Jan 2017 05:38:43 GMT',
  etag: '"c96d2966626f9b68443156ee063e3df7"',
  'x-amz-error-code': 'NoSuchKey',
  'x-amz-error-message': 'The specified key does not exist.',
  'x-amz-error-detail-key': 'mona_jpy/transactions/undefined',
  date: 'Thu, 21 Sep 2017 07:30:36 GMT',
  server: 'AmazonS3',
  age: '10',
  'x-cache': 'Error from cloudfront',
  via: '1.1 a81e162a9acc4a08f8778f221092bb6a.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'Kuy6sALBS-iDc7V7t7lIOsliUHYDi10wmfk4QiLTZpu_phNK1sCXOw==' }
REQUEST reading response's body
REQUEST finish init function https://public.bitbank.cc/mona_jpy/transactions/undefined
REQUEST response end https://public.bitbank.cc/mona_jpy/transactions/undefined 404 { 'content-type': 'text/plain',
  'content-length': '35',
  connection: 'close',
  'last-modified': 'Sun, 08 Jan 2017 05:38:43 GMT',
  etag: '"c96d2966626f9b68443156ee063e3df7"',
  'x-amz-error-code': 'NoSuchKey',
  'x-amz-error-message': 'The specified key does not exist.',
  'x-amz-error-detail-key': 'mona_jpy/transactions/undefined',
  date: 'Thu, 21 Sep 2017 07:30:36 GMT',
  server: 'AmazonS3',
  age: '10',
  'x-cache': 'Error from cloudfront',
  via: '1.1 a81e162a9acc4a08f8778f221092bb6a.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'Kuy6sALBS-iDc7V7t7lIOsliUHYDi10wmfk4QiLTZpu_phNK1sCXOw==' }
REQUEST end event https://public.bitbank.cc/mona_jpy/transactions/undefined
REQUEST has body https://public.bitbank.cc/mona_jpy/transactions/undefined 35
REQUEST emitting complete https://public.bitbank.cc/mona_jpy/transactions/undefined
Error: StatusCodeError: 404 - "{\"success\":0,\"data\":{\"code\":10000}}"
```
